services:
  # --- DATABASE ---
  database:
    container_name: conduit_container_database
    image: postgres:16-alpine
    restart: unless-stopped
    # DB also remains securely isolated within its internal network
    expose:
      - "${DATABASE_PORT}"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # --- FRONTEND ---
  frontend:
    container_name: conduit_container_frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-network
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - frontend_data:/app/data

  # --- BACKEND ---
  backend:
    container_name: conduit_container_backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes are used to persist data and share files between the host and the container. In this case, a volume named conduit-backend is mounted to the /app/db_data directory inside the container. This allows the backend service to store and retrieve data from the database.
    volumes:
      - backend-data:/app/db_data
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    networks:
      - app-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - database

# --- NETWORK & VOLUMES ---
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  backend-data:
  frontend_data: