services:
  # --- DATABASE ---
  database:
    container_name: conduit_container_database
    image: postgres:16-alpine
    restart: unless-stopped
    command: ["postgres", "-c", "password_encryption=md5"]
    # DB also remains securely isolated within its internal network
    expose:
      - "${DATABASE_PORT}"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phppgadmin:
    container_name: conduit_container_phppgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=oberflaechepass
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy

  # --- FRONTEND ---
  frontend:
    container_name: conduit_container_frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8282:80"
    volumes:
      - django-static:/usr/share/nginx/html/static
    networks:
      - app-network
    depends_on:
      - backend

  # --- BACKEND ---
  backend: # This name is used in NGINX in the "proxy_pass" directive
    container_name: conduit_container_backend
    restart: unless-stopped
    user: root
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes are used to persist data and share files between the host and the container. In this case, a volume named conduit-backend is mounted to the /app/db_data directory inside the container. This allows the backend service to store and retrieve data from the database.
    volumes:
      - backend-data:/app/db_data
      - django-static:/app/staticfiles
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    networks:
      - app-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - database

# --- NETWORK & VOLUMES ---
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  backend-data:
  django-static: